### ISSUE TITLE
minimal install instructions in bundle introduction

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/symfony-cmf-docs#403]
as noted in https://github.com/symfony-cmf/symfony-cmf-docs/pull/401/files#r9772706 we should clean up the install sections: only speak about composer, but mention new CmfXyBundle in the app kernel (and particularly list all dependent bundles that need to be instantiated, like KnpMenuBundle or SonataBlockBundle)

@WouterJ does that make sense to you?

**Comment by lsmith77** [comment]
I had a user recently wonder if he needs to register the bundle he just installed. so it does seem to be not obvious but still not sure if its doesnt just clutter the docs for everyone else.

**Comment by dbu** [comment]
fixed in #684

i think that would be stating the obvious for those that know symfony a bit. lets leave it for now, ok?
