### ISSUE TITLE
Show dev branch on symfony.com

### ISSUE THREAD

**Issue by WouterJ** [symfony-cmf/symfony-cmf-docs#417]
@javiereguiluz is it possible that the `master` keyword in the URL shows you the `dev` branch and the `current` keyword the `master` branch when visiting the CMF docs? It would be lovely if we can also see and reference to experimental features.

Besides that, can the version switcher be changed on the CMF docs? A lot of people complain about it being vague that there is a 2.4 version shown (and other 2.x versions) when viewing the 1.0 CMF docs.

**Comment by dbu** [comment]
this is now working

**Comment by javiereguiluz** [comment]
Can we consider this issue solved? Right now I see the following branches in Symfony CMF docs:

![symfony_cmf_branch](https://cloud.githubusercontent.com/assets/73419/9359862/63e70b7a-4693-11e5-94b4-6eb5d1397ac1.png)

In symfony.com docs we have the following configuration:

  * Maintained branches: "1.0", "1.1", "1.2", "master"
  * Master alias: 1.3 (in the URL you see "master", but in the selector you see "1.3")
  * Current alias: 1.2 (in the URL you see "current", but in the selector you see "1.2")

**Comment by WouterJ** [comment]
Good job @javiereguiluz! (do you have any update to whether we can configure this ourselves in the repo instead of pushing you to change something?)

**Comment by javiereguiluz** [comment]
@WouterJ I'm afraid it's not going to be configurable anytime soon. Sorry.
