### ISSUE TITLE
Add live demo

### ISSUE THREAD

**Issue by WouterJ** [symfony-cmf/symfony-cmf-docs#422]
An idea Ryan and I got for the core symfony docs. Travis is already generating the documentation for us, so we can easily push that generated code back to github to let GitHub Pages show us a rendered example of the proposed docs.

I first want to test it on this repo, so expect some nice things to happen in the future :)

Btw, Travis integration is now also merged into the core docs this week!

**Comment by dbu** [comment]
any progress on this? or shall we close it? i think its very difficult to have fully functional demos that actually do something the user can see...

**Comment by WouterJ** [comment]
We now have this available in core with the help of the platform.sh guys, I don't think it's worth doing that for these docs now (as it isn't very active).
