### ISSUE TITLE
How to document enabling

### ISSUE THREAD

**Issue by WouterJ** [symfony-cmf/symfony-cmf-docs#494]
Enabling a persistence layer can be done in various ways. Let's decided on how we do it:

Explicit
---
````yaml
phpcr:
    enabled: true
````
````xml
<phpcr enabled="true" />
````

Using `true`
---
````yaml
phpcr: true
````
````xml
<phpcr />
````

Using `null`
---
````yaml
phpcr: ~
````
````xml
<phpcr />
````

I'm kind of in favor of using `true`, since it's very simple. But it looks very magic when we do things like this when configuring a manager:
````yaml
phpcr:
    manager_name: default
````
````xml
<phpcr manager-name="default" />
````

On the other hand, I thought we also did it in the core docs in one location and I've never heard people asking questions about it.

**Comment by dbu** [comment]
we use canBeEnabled / canBeDisabled in most places, and the enabled attribute with true|false|auto in other places. do we need to do anything more about this in the doc?
