### ISSUE TITLE
Revisiting the doc structure

### ISSUE THREAD

**Issue by wouterj** [symfony-cmf/symfony-cmf-docs#523]
We have "tested" the core structure in the past year(s) and I think we are at the point where we've learned that it doesn't work as well as planned.

There are some main problems:
1. There is a lot of duplication about the main topics. For instance, routing is explained in the quick tour, the book, the bundles and the components.
2. The book has never been a big success
3. The docs try to explain the CMF as a whole, while we are advocating the CMF a seperate parts (which is, imo, a very good thing)
4. A sub section (the "Create a new project using the CMF" tutorial) is more popular than the main section (the book)
5. Users get a disoriented feeling when reading the bundles docs, since part of it is in the Book, part of it in the Bundles and yet another part in the Reference.

I propose to group things about the same topic more together, keeping the tutorial as the article that covers the CMF as a whole. This means:
- [x] Removing the Book
- [x] Removing part of the Cookbook (bundle related stuff)
- [x] Merging the Reference into the Bundle documentation
- [x] Moving the tutorial to a main section "The Tutorial", which replaces the Book.

I would really like to hear your opinions, thoughts and ideas on the issues with the current docs and how we can solve this.

_This issue is, of course, part of the DX initiative._

/cc @dbu @dantleech @lsmith77

**Comment by dbu** [comment]
do we still do something here or leave things as they are now?

**Comment by dbu** [comment]
@WouterJ ok if we close this and continue discussion in #696

**Comment by dbu** [comment]
book removed in #835
