### ISSUE TITLE
The Router - creating a new Route

### ISSUE THREAD

**Issue by marcel-burkhard** [symfony-cmf/symfony-cmf-docs#538]
When following the Tutorial I run into an issue with the proposed implementation of  DataFixtures/PHPCR/LoadRoutingData.php

I described it here (fork):
https://github.com/burki94/symfony-cmf-docs/commit/94a7054025fd48cf2691919ea822c048c2495b00

**Comment by dbu** [comment]
@marcel-burkhard is the problem fixed with https://github.com/symfony-cmf/RoutingAutoBundle/pull/130 ?

**Comment by marcel-burkhard** [comment]
I won't be able to check in the next few days, sorry.

**Comment by dbu** [comment]
its an old issue, so no hurry. do you think you can look into it when you have more time, or no plan to do so?

**Comment by marcel-burkhard** [comment]
unfortunately I don't see this happening anytime soon.
