### ISSUE TITLE
Tutorial: PostAdmin should not extend PageAdmin

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/symfony-cmf-docs#560]
Currently, to save time, the PostAdmin extends PageAdmin but this causes issues later in the tutorial in the "Make Homerpage" section, as the "Make Homepage" button will also appear for Posts, but it will not work.

We should extend a common base class instead, or use traits as previously with `ContentTrait`, e.g. `ContentAdminTrait`.

**Comment by dbu** [comment]
we drop the tutorial from the official doc
