### ISSUE TITLE
Update bundle docs to follow best practices

### ISSUE THREAD

**Issue by wouterj** [symfony-cmf/symfony-cmf-docs#591]
http://symfony.com/doc/current/cookbook/bundles/best_practices.html#installation-instructions

* [x] block #794
* [x] content #810
* [x] core #811
* [x] menu #808
* [x] phpcr_odm #807
* [x] routing #804
* [ ] routing_auto
* [x] seo #805
* [x]  sonata_phpcr_admin_integration
* [x] tree_browser #806

**Comment by dbu** [comment]
indeed. so we should change our examples to use the AppBundle and shorter service names.

i propose we go by bundle chapter to avoid a huge single pull request that will be hard to merge.

**Comment by dbu** [comment]
routing auto doc needs to be written
