### ISSUE TITLE
create docs when for sitemap generation [SeoBundle]

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/symfony-cmf-docs#607]
... when https://github.com/symfony-cmf/SeoBundle/pull/196  is ready.

**Comment by dbu** [comment]
The code is merged. Now its time to write the docs. best we do it while we still remember what we did in the code :-) But i think to *use* the sitemap is a lot easier than to build it...

**Comment by ElectricMaxxx** [comment]
yea btw: there are 3 more features missing to document them:

- error handling #606 
- alternate language #605 

Can be a kind of procastination from my side, but i think i do not have the skills to write docs :-( 
BUT i will try to start them in the evening, so somebody else can fix them.

**Comment by dbu** [comment]
see #683
