### ISSUE TITLE
Edit this page link does not work

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/symfony-cmf-docs#624]
Example: http://symfony.com/doc/current/cmf/index.html

**Comment by dbu** [comment]
@javiereguiluz can you revisit this one please? the link is assuming the tag of the main symfony docs instead of the symfony-cmf docs. the repository is correct, but we have no version 2.7...

**Comment by javiereguiluz** [comment]
I've just pushed some changes to symfony.com website. We need to wait for the review/merge/deploy process, but we could have this problem solved soon.

**Comment by dbu** [comment]
sounds great!

**Comment by WouterJ** [comment]
The link seems to work now
