### ISSUE TITLE
Going back to the TOC in the Creating a basic CMS tutorial

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/symfony-cmf-docs#635]
Currently there is no way to return to the TOC in the tutorial as the sub pages replace the index in the breadcrumb:

The TOC: http://symfony.com/doc/current/cmf/tutorial/index.html
One of the sub pages: http://symfony.com/doc/current/cmf/tutorial/auto-routing.html

**Comment by WouterJ** [comment]
ping @javiereguiluz Has this always been this way. I somewhat remember we have had a period where we did have the full breadcrumb?

**Comment by dbu** [comment]
@javiereguiluz do you have an idea what we could do here? this problem is also occuring when deeper in the cmf bundle documentation - you lose breadcrumbs inside the cmf documentation.

**Comment by WouterJ** [comment]
@javiereguiluz can you please look at this issue?

**Comment by dbu** [comment]
@javiereguiluz are we doing something wrong with the breadcrumbs in the cmf .rst docs? would be good to get breadcrumbs within the cmf doc to help navigation.

**Comment by ElectricMaxxx** [comment]
While `SimpleCmsBundle` was abandoned, this issue ist more relevant. We have to visualize a way to persist content, route and menu without that bundle.

**Comment by dbu** [comment]
the tutorial is going to be integrated into the other docs.
