### ISSUE TITLE
document route validation

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/symfony-cmf-docs#667]
document the validators added in https://github.com/symfony-cmf/RoutingBundle/pull/292

should go into the section "The PHPCR-ODM Route document" of https://github.com/symfony-cmf/symfony-cmf-docs/blob/master/bundles/routing/dynamic.rst, as subsection before talking about admins.

**Comment by dbu** [comment]
@EmmanuelVella it seems you ported the validation from sonata to the forms layer for the routing bundle. may i ask if you would have time to add documentation about them?

**Comment by EmmanuelVella** [comment]
@dbu Sure I will have a look at it.

**Comment by dbu** [comment]
:+1:

**Comment by dbu** [comment]
#694
