### ISSUE TITLE
Annotation warning for using SeoAwareTrait

### ISSUE THREAD

**Issue by ConneXNL** [symfony-cmf/symfony-cmf-docs#669]
http://symfony.com/doc/current/cmf/bundles/seo/seo_aware.html mentions:

"If you are using PHP5.4+ you may also benefit from using the trait SeoAwareTrait to plug these behavior into your model."

I used the trait but after SonataAdminBundle wasn't saving the SEO related object, I realised that using the trait does not automatically add the @PHPCRODM\Child definition on the $seoMetadata.

I am not sure if this should be added in the trait itself or the docs should warn you about the fact that you can't use annotations.

**Comment by dbu** [comment]
lets discuss in https://github.com/symfony-cmf/SeoBundle/issues/229 and
then decide if/how we need to update the documentation

**Comment by WouterJ** [comment]
This is fixed now https://github.com/symfony-cmf/SeoBundle/pull/256 is merged into the CmfSeoBundle.
