### ISSUE TITLE
Documentation for real use case examples

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/symfony-cmf-docs#700]
I had a some talks at the  FrOSCon about the CMF and they gave me a main issue:
The CMF still looks like an easy CMS - install and ready to use. 
But that isn't the truth. The CMF adds CMS functionality into an existing Symfony Application. So we should provide some examples for the integration use cases. For example:

- having an working Symfony Application, where i whant to add some static pages
- having a working Symfony Application, where i whant to add some blog functionality
- having a working Symfony Application, and wanna use some dynamic routing

I know our documentation could give that information as we say in each bundle "just add to your composer.json", but it would be better to really have a point of view starting at an existing syfmony application.

**Comment by dbu** [comment]
i think this is related to the discussion in #696

**Comment by ElectricMaxxx** [comment]
Oh uh, then lets close this one.

**Comment by dbu** [comment]
can you add your points over there and close this one then?
