### ISSUE TITLE
Namespace of DocumentManager

### ISSUE THREAD

**Issue by alexislefebvre** [symfony-cmf/symfony-cmf-docs#733]
On http://symfony.com/doc/current/cmf/bundles/phpcr_odm/fixtures_initializers.html#fixture-loading, a code is given as an example but the namespace for the `DocumentManager` class is not included.

Is `use Doctrine\ODM\PHPCR\DocumentManager;` missing in the code block?

**Comment by dantleech** [comment]
Yes :)
