### ISSUE TITLE
Update versions on symfony.com

### ISSUE THREAD

**Issue by wouterj** [symfony-cmf/symfony-cmf-docs#753]
@javiereguiluz can you please make the following changes on symfony.com?

 * `1.2` should point to the 1.2 branch
 * `current / 1.3` should point to the 1.3 branch
 * `master / 2.0` should point to the master branch

Please also note that there currently is *no link* to the CMF docs anywhere in the documentation indices (not even the 3rd party bundles index).

**Comment by WouterJ** [comment]
Ping @javiereguiluz, can you please update this?

**Comment by javiereguiluz** [comment]
I've just changed this in symfony.com app and it will be online after the next deploy. I'm sorry it took me so long.
