### ISSUE TITLE
'DOWNLOAD AS PDF' link not working

### ISSUE THREAD

**Issue by abhinavkumar940** [symfony-cmf/symfony-cmf-docs#768]
Page URL: http://symfony.com/doc/master/cmf/index.html

Currently the download button links to http://symfony.com/pdf/Symfony_cmf_2.0.pdf?v=4 which appears to be a dead link

**Comment by dbu** [comment]
its not part of this repository but added during the build process of symfony.com, afaik.
@weaverryan can you fix this? or who can?

**Comment by wouterj** [comment]
@javiereguiluz is the man to contact for all symfony.com internals stuff, like this :)

**Comment by abhinavkumar940** [comment]
No problem @javiereguiluz

**Comment by dbu** [comment]
@javiereguiluz any updates on this one? just checked and it does not work. maybe you could hide the download link until this is fixed?

**Comment by dbu** [comment]
ping @javiereguiluz

**Comment by dbu** [comment]
i noticed that this works again.
