### ISSUE TITLE
Throughly review Quick Tour

### ISSUE THREAD

**Issue by wouterj** [symfony-cmf/symfony-cmf-docs#788]
This is for newcomers, it should be 100% correct before the 2.0 release.

* [ ] Make sure the examples work
* [ ] Follow the symfony best practices (see #591)
* [ ] Do not use unmaintained components

**Comment by ElectricMaxxx** [comment]
[WIP] 
- replace confusing version hint caused byAppBundle example
- you do normally setup a db ina common Symfony App -> go into it as kind of an extension "Setting up DB"
- remove create stuff as it is currently not supported, ddo not forget request graph
- "Adding new Page" confuses by the use of a fixture loader and not calling it so. yml ->DB is for a short example
- Live Editing should be removed until we support it again
- Creating Page with code: Fixture Loader is a way to visualize for us, it is not the way to handle our models -> point on own admin or our sonata
- do not use simple cms for the route ecample, simplest: persist route with defaults containing _controller -> no content needed -> better route definitions than static ones
-update sonata section: ours in a separate bundle, update image

**Comment by dbu** [comment]
the quick tour relied on the standard edition having the AcmeDemoBundle, but we removed that in version 1.3.

we should fix the quick tour to use the newest version of the cmf. either make it work without the demo bundle, or first tell people to install the acme demo bundle into their project, or switch to the sandbox.
#766 locked the standard edition to a version that has AcmeDemoBundle as a quickfix.

**Comment by dbu** [comment]
started in #802

**Comment by dbu** [comment]
quick tour is updated
