### ISSUE TITLE
Mention abandoned packages in their documentation

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/symfony-cmf-docs#792]
I do not whant to remove their docs as the docs are correct until we stopped maintaining, but we should add a kind of a hint to mark the abandoned. And we should explain what that means:

* older versions still work until we stoped maintaining
* except bug no one is able to care atm
* "you would like to maintain?"

**Comment by dbu** [comment]
i would use the term "currently unmaintained" instead of abandoned, to
make our intention clear.

**Comment by ElectricMaxxx** [comment]
Easier for me to write and speak too. -------- Originalnachricht --------Betreff: Re: [symfony-cmf/symfony-cmf-docs] Mention abandoned packages in their documentation (#792)Von: David Buchmann An: symfony-cmf/symfony-cmf-docs Cc: Maximilian Berghoff ,Author i would use the term "currently unmaintained" instead of abandoned, to
make our intention clear.


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/symfony-cmf/symfony-cmf-docs","title":"symfony-cmf/symfony-cmf-docs","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/symfony-cmf/symfony-cmf-docs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dbu in #792: i would use the term \"currently unmaintained\" instead of abandoned, to\nmake our intention clear.\n"}],"action":{"name":"View Issue","url":"https://github.com/symfony-cmf/symfony-cmf-docs/issues/792#issuecomment-272790001"}}}
