### ISSUE TITLE
Link to spam site from main page

### ISSUE THREAD

**Issue by blowski** [symfony-cmf/symfony-cmf-docs#861]
On https://symfony.com/doc/current/cmf/index.html, there is a link to "decoupled CMS" in the opening paragraph, but the site appears to have been replaced by spam content.

<img width="724" alt="image" src="https://user-images.githubusercontent.com/752199/79063324-df36b880-7c98-11ea-856e-505fe37bc12e.png">

links to

<img width="783" alt="image" src="https://user-images.githubusercontent.com/752199/79063337-ecec3e00-7c98-11ea-8c86-1d857a2633b6.png">

**Comment by dbu** [comment]
this has been fixed in #860 but it seems the website does not reflect it. i have now put the change into all branches instead of only master. lets see if that helps

**Comment by blowski** [comment]
That PR doesn't look like it's the same link? https://github.com/symfony-cmf/symfony-cmf-docs/pull/860 is talking about a link to http://demo.createphp.org/, but this ticket is a link to http://decoupledcms.org/.

**Comment by dbu** [comment]
ups, i misread the PR that i linked. but i did cherry-pick the right commit that was about decoupledcms ;-)

**Comment by dbu** [comment]
@javiereguiluz can you see a problem with the symfony cmf doc building? or am i just not patient enough? i still see the old bad link even though it should be changed in all branches...

**Comment by wouterj** [comment]
@dbu I believe the docs are rebuild every 4 hours (independently of changes)

**Comment by dbu** [comment]
if they build every 4 hours, something is broken. its now 6 hours ago and still not updated.

**Comment by javiereguiluz** [comment]
I can now see the right link, so I guess this is solved. Sorry it took a bit ... docs are rebuilt every few hours and there's also the cache of doc pages, etc.

**Comment by dbu** [comment]
yep, its fine now. thanks a lot y'all!
